### ISSUE TITLE
Totally broken on Firefox 42 betas

### ISSUE THREAD

**Issue by hmijail** [jcooley/lingodisco-firefox-addon#2]
I installed lingodisco a few betas ago, and I have never seen it working. There is the disco ball in the toolbar, but clicking it puts a red square inside it, and shows a small pane which only says "on", "toggle_disable_id", "nothing_translated_id".

**Comment by jcooley** [comment]
I can see the same issue. There does not seem to be an obvious fix as there is no error shown. Firefox 43a has the issue too. Pull requests welcome.

**Comment by jcooley** [comment]
I had created "var data = self.data;" to alias the data library. This seems to have stopped working with FF42. I submitted version 1.0.3 to fix this. Hopefully it should be reviewed before FF42 is released next week. Thanks for the bug report.

**Comment by hmijail** [comment]
I am now in FF42 with lingodisco 1.0.3. Clicking on the ball now shows a dialog, but when clicking on the "edit" button, a big empty "window" appears and nothing else happens. Clicking out of the window dismisses it.

**Comment by jcooley** [comment]
I tried it on different Linux machines and I don't see the issue. Could you try with a different firefox profile to eliminate your config? Using "firefox -P --no-remote" is a good way to try a different profile.

**Comment by hmijail** [comment]
I finally could try it in a new profile with only LingoDisco installed, and it worked.
In my normal profile I have NoScript and Privacy Badger installed (and lots of other things), so I guess the problems can be related to them.
